version = 1
name = "zen-meditation"

[setup]
script = "pnpm install --frozen-lockfile && pnpm run prebuild"

[[actions]]
name = "Run IOS"
icon = "run"
command = "pnpm ios"

[[actions]]
name = "Run Android"
icon = "run"
command = "pnpm android"

[[actions]]
name = "Check"
icon = "tool"
command = "pnpm run check"

[[actions]]
name = "Test"
icon = "test"
command = "pnpm test"

[[actions]]
name = "Typecheck"
icon = "check"
command = "pnpm typecheck"
